### ISSUE TITLE
Cloudwatch metrics streams missing tags dimensions  

### ISSUE THREAD

**Issue by maksimize** [aws-observability/aws-o11y-recipes#50]
As an Observability engineer, I would like to be able to filter metric results using resource tags to be able to have group elements form the same resource
example: cpu utilization of all ec2 instances with the tag team:teamX

**Comment by tomaszwaws** [comment]
I am looking into it

**Comment by mhausenblas** [comment]
This is addressed with @tomaszwaws PR #54
